accounts/urls.py
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy
from django_pydenticon.views import image as pydenticon_image
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('logout/',views.logout,name="logout"),
    # path('password_change/', auth_views.PasswordChangeView.as_view(
    #     success_url =reverse_lazy('password_change')
    # ), name='password_change'),
    path('password_change/',views.password_change,name='password_change'),
    # /accounts/login/=>j settings.LOGIN_URL
    path('login/', views.login, name="login"),
    path('identicon/image/<path:data>/', pydenticon_image,name="pydenticon_image"),
    path('edit/', views.profile_edit, name="profile_edit"),
]

baseApp/urls.py
from django.urls import path
from baseApp import views

app_name = 'baseApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/',views.post_new,name='post_new'),
    path('post/prod/', views.post_list_prod, name='post_list_prod'),
    path('post/project/', views.post_list_project, name='post_list_project'),
    path('post/prod/<int:pk>/',views.post_detail_prod,name='post_detail_prod'),
    path('post/project/<int:pk>/',views.post_detail_project,name='post_detail_project'),
    # path('post/<int:pk>/like',views.post_like,name='post_like'),
    # path('post/<int:pk>/unlike',views.post_unlike,name='post_unlike'),
    # path('post/<int:post_pk>/comment/new',views.comment_new,name='comment_new'),
    # re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page,name='user_page'),
]

moonsoft/urls.py
from re import template

from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('baseApp/', include('baseApp.urls')),
    path('', RedirectView.as_view(pattern_name='baseApp:index'), name='root'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static (settings.STATIC_URL, document_root = settings.STATIC_ROOT)



if settings.DEBUG:
    print(settings.DEBUG)
    import debug_toolbar
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL,
                   document_root=settings.MEDIA_ROOT)

moonsoft/views.py
from django.contrib.auth.views import LoginView

# login = LoginView.as_view(template_name="_form.html")

moonsoft/templates/_fileForm.html
{% load bootstrap4 %}
<div class="card">
  {% if  form_title %}
    <div class="card-header">
        {{form_title}}
    </div>
  {% endif %}
  <div class="card-body">
        {% if  form %}
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form%}
                <div id="images" class="img-fluid"></div>
{#                <input type="button" class="btn btn-primary mt-3" name="add_image" id="add_image" value="Add Image">#}
                <input type="button" class="btn btn-secondary" name="add_image" id="add_image" value="Add Image" style="width: 100%;margin-bottom: 10px"/>
                {% buttons %}
                    <button type="submit" class="btn btn-primary " style="width: 100%;">
                        {{ submit_label|default:'Submit'}}
                    </button>
                {% endbuttons %}
            </form>
        {% else %}
            <div class="alert alert-danger">
                폼객체를 지정해 주세요.
            </div>
        {% endif %}

    </div>
</div>
<script>
    document.getElementById("add_image").onclick=function (ev) {
        var image=document.getElementById("images");
        var preview=document.createElement("img");
        preview.style.width="auto";
        preview.style.height="100px";
        var newInput=document.createElement("input");
        newInput.type="file";
        newInput.name="file[]";
        newInput.className="file-upload";
        var br=document.createElement("br");
        var br1=document.createElement("br");

        newInput.onchange=function (ev1) {
            if(this.files && this.files[0]){
                var fileReader=new FileReader();
                fileReader.onload=function (ev2) {
                    preview.src=ev2.target.result;
                };
                fileReader.readAsDataURL(this.files[0])
            }
        };
        image.appendChild(preview);
        image.appendChild(newInput);
        image.appendChild(br);
        image.appendChild(br1);
    }
</script>

moonsoft/templates/_form.html
{% load bootstrap4 %}


<div class="card">
  {% if  form_title %}
    <div class="card-header">
        {{form_title}}
    </div>
  {% endif %}
  <div class="card-body">
        {% if  form %}
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form%}
                {% buttons %}
                    <button type="submit" class="btn btn-primary " style="width: 100%;">
                    {{ submit_label|default:'Submit'}}
                    </button>
                {% endbuttons %}
            </form>
        {% else %}
            <div class="alert alert-danger">
                폼객체를 지정해 주세요.
            </div>
        {% endif %}

    </div>
</div>

moonsoft/templates/layout.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Title -->
  <title>문소프트에 오신걸 환영 합니다.</title>

  <!-- Required Meta Tags Always Come First -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'bootstrap-5.0.0-dist/css/bootstrap.css' %}"/>

  <script src="{% static 'bootstrap-5.0.0-dist/js/bootstrap.js' %}"></script>
  <!-- Favicon -->
  <link rel="shortcut icon" href="../../favicon.ico">

  <!-- Google Fonts -->
  <link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">

  <!-- CSS Implementing Plugins -->
{#  <link rel="stylesheet" href="{% static 'customize/assets/vendor/font-awesome/css/all.min.css' %}">#}
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/hs-megamenu/src/hs.megamenu.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/custombox/dist/custombox.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/animate.css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/slick-carousel/slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/fancybox/jquery.fancybox.css' %}">

  <!-- CSS Space Template -->
  <link rel="stylesheet" href="{% static 'customize/assets/css/theme.css' %}">
</head>

<body>
  <!-- Skippy -->
  <a id="skippy" class="r-onlysr-only s-focusable u-skippy" href="#content">
    <div class="container">
      <span class="u-skiplink-text">Skip to main content</span>
    </div>
  </a>
  <!-- End Skippy -->

  <!-- ========== HEADER ==========  TODO : 클래스만 변경 하는 방법 구상-->
  <header id="header" class="u-header u-header--modern u-header--bordered u-header--bg-transparent u-header--white-nav-links u-header--sticky-top-lg">
  {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    <div class="u-header__section">

      <div id="logoAndNav" class="container-fluid">

        <!-- Nav -->
        <nav class="js-mega-menu navbar navbar-expand-lg u-header__navbar">
          <!-- Logo -->
          <div class="u-header__navbar-brand-wrapper">
            <a class="navbar-brand" href="{% url 'baseApp:index' %}" aria-label="Space">
<!--                <img src="https://doubljungdd.blob.core.windows.net/static/mainImage/moonSoftMain/moonsoftlogo.png" alt="Logo" style="width: 45px; height: 45px;">-->
                <img src="{% static 'mainImage/moonSoftMain/moonsoftlogo.png' %}" alt="Logo" style="width: 45px; height: 45px;">
                <span class="u-header__navbar-brand-default text-white" style="font-size: 20px;" ><strong>MOONSOFT</strong></span>
                <span class="u-header__navbar-brand-on-scroll text-dark" style="font-size: 20px;" ><strong>MOONSOFT</strong></span>
                <span class="u-header__navbar-brand-mobile" style="font-size: 20px;" ><strong>MOONSOFT</strong></span>
<!--{#              <img class="u-header__navbar-brand-default" src="{% static 'customize/assets/svg/logos/logo-white.svg' %}" alt="Logo">#}-->
<!--{#              <img class="u-header__navbar-brand-on-scroll" src="{% static 'customize/assets/svg/logos/logo.svg' %}" alt="Logo">#}-->
<!--{#              <img class="u-header__navbar-brand-mobile" src="{% static 'customize/assets/svg/logos/logo-short.svg' %}" alt="Logo">#}-->
            </a>
          </div>
          <!-- End Logo -->

          <!-- Responsive Toggle Button -->
          <button type="button" class="navbar-toggler btn u-hamburger u-header__hamburger"
                  aria-label="Toggle navigation"
                  aria-expanded="false"
                  aria-controls="navBar"
                  data-toggle="collapse"
                  data-target="#navBar">
            <span class="d-none d-sm-inline-block">Menu</span>
            <span id="hamburgerTrigger" class="u-hamburger__box ml-3">
              <span class="u-hamburger__inner"></span>
            </span>
          </button>
          <!-- End Responsive Toggle Button -->

          <!-- Navigation -->
          <div id="navBar" class="collapse navbar-collapse u-header__navbar-collapse py-0">
            <ul class="navbar-nav u-header__navbar-nav">
              <!-- Home dropdown-item u-header__sub-menu-list-item"-->
              <li class="u-header__sub-menu-list-item" >
                <a id="homeMegaMenu" class="nav-link u-header__nav-link" href="{% url 'baseApp:index' %}"
                   aria-haspopup="true"
                   aria-expanded="false"
                   aria-labelledby="homeSubMenu">
                  Home
                </a>
              </li>
              <!-- End Home -->

              <!-- Pages -->
              <li class="u-header__sub-menu-list-item" >
                <a id="PagesMegaMenu" class="nav-link u-header__nav-link" href="{% url 'baseApp:post_list_prod' %}"
                   aria-haspopup="true"
                   aria-expanded="false">
                  Products
                </a>
              </li>
              <!-- End Pages -->

              <!-- Projects -->
              <li class="u-header__sub-menu-list-item" >
                <a id="worksMegaMenu" class="nav-link u-header__nav-link" href="{% url 'baseApp:post_list_project' %}"
                   aria-haspopup="true"
                   aria-expanded="false"
                   aria-labelledby="worksSubMenu">
                  Projects
                </a>
              </li>
              <!-- Projects Works -->


              <!-- Button -->
                {% if not user.is_authenticated %}
              <li class="nav-item u-header__nav-item-btn">
                  <a class="btn btn-sm btn-primary"  href="{% url 'accounts:login' %}" role="button"
                     data-overlay-color="#151b26">
                  <i class="fa fa-user-circle mr-1"></i>
                  Login
                </a>
              </li>
              {% else %}
              <li class="nav-item u-header__nav-item-btn">
                <a class="btn btn-sm btn-secondary" href="{% url 'accounts:logout' %}" role="button"
                   data-overlay-color="#151b26">
                  <i class="bi-person mr-1"></i>
                  Logout
                </a>
              </li>
              {% endif %}
              <!-- End Button -->
            </ul>
          </div>
          <!-- End Navigation -->
        </nav>
        <!-- End Nav -->
      </div>
    </div>
  </header>
  <!-- ========== END HEADER ========== -->
{% block content %}
{% endblock %}
  <!-- ========== FOOTER ========== -->
  <footer class="bg-dark">
    <div class="container space-2">
      <div class="">

        <div class="">
          <!-- End Language -->
           <div class="text-white">대전시 유성구 반석동로 54, 센타프라자3, 303호 </div>
           <div class="text-white">© MOOONSOFT</div>
        </div>
    </div>
    </div>
  </footer>
  <!-- ========== END FOOTER ========== -->

  <!-- Go to Top -->

  <!-- End Go to Top -->

  <!-- JS Global Compulsory -->
  <script src="{% static 'customize/assets/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/jquery-migrate/dist/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/popper.js/dist/umd/popper.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/bootstrap/bootstrap.min.js' %}"></script>

  <!-- JS Implementing Plugins -->
  <script src="{% static 'customize/assets/vendor/hs-megamenu/src/hs.megamenu.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/jquery-validation/dist/jquery.validate.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/custombox/dist/custombox.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/custombox/dist/custombox.legacy.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/slick-carousel/slick/slick.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/fancybox/jquery.fancybox.min.js' %}"></script>

  <!-- JS Space -->
  <script src="{% static 'customize/assets/js/hs.core.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.header.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.unfold.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.validation.js' %}"></script>
  <script src="{% static 'customize/assets/js/helpers/hs.focus-state.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.malihu-scrollbar.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.modal-window.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.show-animation.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.slick-carousel.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.fancybox.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.go-to.js' %}"></script>

  <!-- JS Plugins Init. -->
  <script>

    $(window).on('load', function () {
      // initialization of HSMegaMenu component
      $('.js-mega-menu').HSMegaMenu({
        event: 'hover',
        pageContainer: $('.container'),
        breakpoint: 991,
        hideTimeOut: 0
      });
    });

    $(document).on('ready', function () {
      // initialization of header
      $.HSCore.components.HSHeader.init($('#header'));

      // initialization of unfold component
      $.HSCore.components.HSUnfold.init($('[data-unfold-target]'), {
        afterOpen: function () {
          if (!$('body').hasClass('IE11')) {
            $(this).find('input[type="search"]').focus();
          }
        }
      });

      // initialization of form validation
      $.HSCore.components.HSValidation.init('.js-validate', {
        rules: {
          confirmPassword: {
            equalTo: '#password'
          }
        }
      });

      // initialization of forms
      $.HSCore.helpers.HSFocusState.init();

      // initialization of malihu scrollbar
      $.HSCore.components.HSMalihuScrollBar.init($('.js-scrollbar'));

      // initialization of autonomous popups
      $.HSCore.components.HSModalWindow.init('[data-modal-target]', '.js-signup-modal', {
        autonomous: true
      });

      // initialization of show animations
      $.HSCore.components.HSShowAnimation.init('.js-animation-link');

      // initialization of slick carousel
      $.HSCore.components.HSSlickCarousel.init('.js-slick-carousel');

      // initialization of fancybox
      $.HSCore.components.HSFancyBox.init('.js-fancybox');

      // initialization of go to
      $.HSCore.components.HSGoTo.init('.js-go-to');
    });
  </script>
</body>
</html>

moonsoft/templates/layout_post.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Title -->
  <title>문소프트에 오신걸 환영 합니다.</title>

  <!-- Required Meta Tags Always Come First -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'bootstrap-5.0.0-dist/css/bootstrap.css' %}"/>
  <script src="{% static 'jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'bootstrap-5.0.0-dist/js/bootstrap.js' %}"></script>
  <!-- Favicon -->
  <link rel="shortcut icon" href="../../favicon.ico">

  <!-- Google Fonts -->
  <link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">

  <!-- CSS Implementing Plugins -->
{#  <link rel="stylesheet" href="{% static 'customize/assets/vendor/font-awesome/css/all.min.css' %}">#}
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/hs-megamenu/src/hs.megamenu.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/custombox/dist/custombox.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/animate.css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/slick-carousel/slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/fancybox/jquery.fancybox.css' %}">

  <!-- CSS Space Template -->
  <link rel="stylesheet" href="{% static 'customize/assets/css/theme.css' %}">
</head>

<body>
  <!-- Skippy -->
  <a id="skippy" class="sr-only sr-only-focusable u-skippy" href="#content">
    <div class="container">
      <span class="u-skiplink-text">Skip to main content</span>
    </div>
  </a>
  <!-- End Skippy -->

  <!-- ========== HEADER ========== -->
  <header id="header" class="u-header u-header--modern u-header--bordered u-header--sticky-top-lg">
  {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    <div class="u-header__section">

      <div id="logoAndNav" class="container-fluid">

        <!-- Nav -->
        <nav class="js-mega-menu navbar navbar-expand-lg u-header__navbar">
          <!-- Logo -->
          <div class="u-header__navbar-brand-wrapper">
            <a class="navbar-brand" href="{% url 'baseApp:index' %}" aria-label="Space">
<!--                <img src="https://doubljungdd.blob.core.windows.net/static/mainImage/moonSoftMain/moonsoftlogo.png" alt="Logo" style="width: 45px; height: 45px;">-->
                <img src="{% static 'mainImage/moonSoftMain/moonsoftlogo.png' %}" alt="Logo" style="width: 45px; height: 45px;">
                <span class="u-header__navbar-brand-default text-dark" style="font-size: 20px;" ><strong>MOONSOFT</strong></span>
                <span class="u-header__navbar-brand-mobile" style="font-size: 20px;" ><strong>MOONSOFT</strong></span>
<!--              <img class="u-header__navbar-brand-default" src="{% static 'customize/assets/svg/logos/logo-white.svg' %}" alt="Logo">-->
<!--              <img class="u-header__navbar-brand-on-scroll" src="{% static 'customize/assets/svg/logos/logo.svg' %}" alt="Logo">-->
<!--              <img class="u-header__navbar-brand-mobile" src="{% static 'customize/assets/svg/logos/logo-short.svg' %}" alt="Logo">-->
            </a>
          </div>
          <!-- End Logo -->

          <!-- Responsive Toggle Button -->
          <button type="button" class="navbar-toggler btn u-hamburger u-header__hamburger"
                  aria-label="Toggle navigation"
                  aria-expanded="false"
                  aria-controls="navBar"
                  data-toggle="collapse"
                  data-target="#navBar">
            <span class="d-none d-sm-inline-block">Menu</span>
            <span id="hamburgerTrigger" class="u-hamburger__box ml-3">
              <span class="u-hamburger__inner"></span>
            </span>
          </button>
          <!-- End Responsive Toggle Button -->

          <!-- Navigation -->
          <div id="navBar" class="collapse navbar-collapse u-header__navbar-collapse py-0">
            <ul class="navbar-nav u-header__navbar-nav">
              <!-- Home -->
              <li class="u-header__sub-menu-list-item" >
                <a id="homeMegaMenu" class="nav-link u-header__nav-link" href="{% url 'baseApp:index' %}"
                   aria-haspopup="true"
                   aria-expanded="false"
                   aria-labelledby="homeSubMenu">
                  Home
                </a>
              </li>
              <!-- End Home -->

              <!-- Pages -->
              <li class="u-header__sub-menu-list-item" >
                <a id="PagesMegaMenu" class="nav-link u-header__nav-link" href="{% url 'baseApp:post_list_prod' %}"
                   aria-haspopup="true"
                   aria-expanded="false">
                  Products
                </a>
              </li>
              <!-- End Pages -->

              <!-- Projects -->
              <li class="u-header__sub-menu-list-item" >
                <a id="worksMegaMenu" class="nav-link u-header__nav-link" href="{% url 'baseApp:post_list_project' %}"
                   aria-haspopup="true"
                   aria-expanded="false"
                   aria-labelledby="worksSubMenu">
                  Projects
                </a>
              </li>

                {% if not user.is_authenticated %}
              <li class="nav-item u-header__nav-item-btn">
                  <a class="btn btn-sm btn-primary"  href="{% url 'accounts:login' %}" role="button"
{#                     data-modal-target="#signupModal"#}
                     data-overlay-color="#151b26">
                  <i class="fa fa-user-circle mr-1"></i>
                  Login
                </a>
              </li>
              {% else %}
              <li class="nav-item u-header__nav-item-btn">
                <a class="btn btn-sm btn-secondary" href="{% url 'accounts:logout' %}" role="button"
                   data-overlay-color="#151b26">
                  <i class="fa fa-user-circle mr-1"></i>
                  Logout
                </a>
              </li>
              {% endif %}
              <!-- End Button -->
            </ul>
          </div>
          <!-- End Navigation -->
        </nav>
        <!-- End Nav -->
      </div>
    </div>
  </header>
  <!-- ========== END HEADER ========== -->
{% block content %}
{% endblock %}
  <!-- ========== FOOTER ========== -->
   <footer class="bg-dark">
    <div class="container space-2">
      <div class="">
        <div class="">
           <div class="text-white">대전시 유성구 반석동로 54, 센타프라자3, 303호 </div>
           <div class="text-white">© MOOONSOFT</div>
        </div>
      </div>
    </div>
  </footer>
  <!-- ========== END FOOTER ========== -->
  <!-- End Go to Top -->

  <!-- JS Global Compulsory -->
  <script src="{% static 'customize/assets/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/jquery-migrate/dist/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/popper.js/dist/umd/popper.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/bootstrap/bootstrap.min.js' %}"></script>

  <!-- JS Implementing Plugins -->
  <script src="{% static 'customize/assets/vendor/hs-megamenu/src/hs.megamenu.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/jquery-validation/dist/jquery.validate.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/custombox/dist/custombox.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/custombox/dist/custombox.legacy.min.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/slick-carousel/slick/slick.js' %}"></script>
  <script src="{% static 'customize/assets/vendor/fancybox/jquery.fancybox.min.js' %}"></script>

  <!-- JS Space -->
  <script src="{% static 'customize/assets/js/hs.core.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.header.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.unfold.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.validation.js' %}"></script>
  <script src="{% static 'customize/assets/js/helpers/hs.focus-state.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.malihu-scrollbar.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.modal-window.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.show-animation.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.slick-carousel.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.fancybox.js' %}"></script>
  <script src="{% static 'customize/assets/js/components/hs.go-to.js' %}"></script>

  <!-- JS Plugins Init. -->
  <script>
    $(window).on('load', function () {
      // initialization of HSMegaMenu component
      $('.js-mega-menu').HSMegaMenu({
        event: 'hover',
        pageContainer: $('.container'),
        breakpoint: 991,
        hideTimeOut: 0
      });
    });

    $(document).on('ready', function () {
      // initialization of header
      $.HSCore.components.HSHeader.init($('#header'));

      // initialization of unfold component
      $.HSCore.components.HSUnfold.init($('[data-unfold-target]'), {
        afterOpen: function () {
          if (!$('body').hasClass('IE11')) {
            $(this).find('input[type="search"]').focus();
          }
        }
      });

      // initialization of form validation
      $.HSCore.components.HSValidation.init('.js-validate', {
        rules: {
          confirmPassword: {
            equalTo: '#password'
          }
        }
      });

      // initialization of forms
      $.HSCore.helpers.HSFocusState.init();

      // initialization of malihu scrollbar
      $.HSCore.components.HSMalihuScrollBar.init($('.js-scrollbar'));

      // initialization of autonomous popups
      $.HSCore.components.HSModalWindow.init('[data-modal-target]', '.js-signup-modal', {
        autonomous: true
      });

      // initialization of show animations
      $.HSCore.components.HSShowAnimation.init('.js-animation-link');

      // initialization of slick carousel
      $.HSCore.components.HSSlickCarousel.init('.js-slick-carousel');

      // initialization of fancybox
      $.HSCore.components.HSFancyBox.init('.js-fancybox');

      // initialization of go to
      $.HSCore.components.HSGoTo.init('.js-go-to');
    });
  </script>
</body>
</html>