accounts/urls.py
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy
from django_pydenticon.views import image as pydenticon_image
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('logout/',views.logout,name="logout"),
    # path('password_change/', auth_views.PasswordChangeView.as_view(
    #     success_url =reverse_lazy('password_change')
    # ), name='password_change'),
    path('password_change/',views.password_change,name='password_change'),
    # /accounts/login/=>j settings.LOGIN_URL
    path('login/', views.login, name="login"),
    path('identicon/image/<path:data>/', pydenticon_image,name="pydenticon_image"),
    path('edit/', views.profile_edit, name="profile_edit"),
]

baseApp/urls.py
from django.urls import path
from baseApp import views

app_name = 'baseApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/',views.post_new,name='post_new'),
    path('post/prod/', views.post_list_prod, name='post_list_prod'),
    path('post/project/', views.post_list_project, name='post_list_project'),
    path('post/prod/<int:pk>/',views.post_detail_prod,name='post_detail_prod'),
    path('post/project/<int:pk>/',views.post_detail_project,name='post_detail_project'),
    # path('post/<int:pk>/like',views.post_like,name='post_like'),
    # path('post/<int:pk>/unlike',views.post_unlike,name='post_unlike'),
    # path('post/<int:post_pk>/comment/new',views.comment_new,name='comment_new'),
    # re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page,name='user_page'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.shortcuts import resolve_url
# Create your models here.


class User(AbstractUser):

    pass

accounts/views.py
from re import template

from django.contrib.auth.hashers import check_password, make_password
from django.http import HttpResponseRedirect

from accounts.form import SignupForm, ProfileForm, PasswordChangeForm
from django.shortcuts import get_object_or_404, redirect, render

from django.contrib.auth.decorators import login_required
from django.contrib import messages, auth
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, logout_then_login,
    PasswordChangeView as AuthPasswordChangeView
)

from django.contrib.auth import get_user_model, login as auth_login, authenticate

User = get_user_model

# Create your views here.

# login = LoginView.as_view(template_name="accounts/login_form.html")
login = LoginView.as_view(template_name="accounts/login_form.html")
# def login(request):
#     print(request.POST)
#     username = request.POST['username']
#     password = request.POST['password']
#     print(username)
#     print(password)
#     user = auth.authenticate(request, username=username, password=password)
#     print(user)
#     if user is not None:
#         messages.error(request, '로그인에 실패 하셨습니다.')
#         login(request, user)
#         return redirect('/')
#     else:
#         messages.error(request, '로그인에 실패 하셨습니다.')
#         return redirect('accounts/login_form.html')

# logout = LogoutView.as_view()
# logout = LogoutView.as_view(template_name ="accounts/login_form.html")

def logout(request):
    messages.success(request, '로그아웃 되었습니다.')
    auth.logout(request)
    return redirect('/')
    # return logout_then_login('/')


def signup(request):
    print("signup")
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            signup_user = form.save()
            auth_login(request, signup_user)
            messages.success(request, "회원가입 환영합니다.")
            next_url = request.GET.get('next', '/')
            return redirect(next_url)
    else:
        form = SignupForm()

    return render(request, 'accounts/signup_form.html', {
        'form': form
    })


@login_required
def profile_edit(request):
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid:
            form.save()
            messages.success(request, "프로파일이 수정/저장되었습니다.")
            return redirect("profile_edit")
    else:
        form = ProfileForm(instance=request.user)
    return render(request, "accounts/profile_edit_form.html", {
        'form': form,
    })


class PasswordCheangeView(LoginRequiredMixin, AuthPasswordChangeView):
    success_url = reverse_lazy('password_change')
    template_name = "accounts/password_change_form.html"
    form_class = PasswordChangeForm

    def form_valid(self, form):
        messages.success(self.request, "암호를 변경 했습니다.")
        return super().form_valid(form)


password_change = PasswordCheangeView.as_view()

accounts/templates/accounts/layout.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Title -->
  <title>로그인</title>

  <!-- Required Meta Tags Always Come First -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'bootstrap-5.0.0-dist/css/bootstrap.css' %}"/>
  <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'bootstrap-5.0.0-dist/js/bootstrap.js' %}"></script>
  <!-- Favicon -->
  <link rel="shortcut icon" href="../../favicon.ico">

  <!-- Google Fonts -->
  <link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">

  <!-- CSS Implementing Plugins -->
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/font-awesome/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/hs-megamenu/src/hs.megamenu.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/custombox/dist/custombox.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/animate.css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/slick-carousel/slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/fancybox/jquery.fancybox.css' %}">

  <!-- CSS Space Template -->
  <link rel="stylesheet" href="{% static 'customize/assets/css/theme.css' %}">
</head>
<body>
<!-- Content -->
    <div class="container mt-lg-9">
        <div class="row">
            <div class="col-sm-6 offset-md-3">
                <div class="card">
                      <div class="p-5 bg-white rounded">
                          <div class="card-body">
                                {% block content %}
                                {% endblock %}
                          </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

accounts/templates/accounts/login.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Title -->
  <title>로그인</title>

  <!-- Required Meta Tags Always Come First -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'bootstrap-5.0.0-dist/css/bootstrap.css' %}"/>
  <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'bootstrap-5.0.0-dist/js/bootstrap.js' %}"></script>
  <!-- Favicon -->
  <link rel="shortcut icon" href="../../favicon.ico">

  <!-- Google Fonts -->
  <link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">

  <!-- CSS Implementing Plugins -->
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/font-awesome/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/hs-megamenu/src/hs.megamenu.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/custombox/dist/custombox.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/animate.css/animate.min.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/slick-carousel/slick/slick.css' %}">
  <link rel="stylesheet" href="{% static 'customize/assets/vendor/fancybox/jquery.fancybox.css' %}">

  <!-- CSS Space Template -->
  <link rel="stylesheet" href="{% static 'customize/assets/css/theme.css' %}">
</head>
<body>
<!-- Content -->
    <div class="container mt-lg-9">
        <div class="row">
            <div class="col-sm-6 offset-md-3">
                <div class="card">
                      <div class="p-5 bg-white rounded">
                          <div class="card-body">
                                <form action="" method="post" enctype="multipart/form-data">
                                    <div id="signin" data-target-group="idForm">
                                      <!-- Title -->
                                          <header class="text-center mb-5">
                                            <h2 class="h4 mb-0">Please sign in</h2>
                                            <p>Signin to manage your account.</p>
                                          </header>
                                          <!-- End Title -->
                                        {% csrf_token %}
                                        {% bootstrap_form form%}
                                         <div class="mb-3">
                                            <button type="submit" class="btn btn-block btn-primary">로그인</button>
                                         </div>

                                      <div class="text-center mb-3">
                                        <p class="text-muted">
                                          계정이 없으신가요?
                                          <a class="js-animation-link" href="{% url 'accounts:signup' %}"
                                             data-link-group="idForm"
                                             data-animation-in="fadeIn">회원가입
                                          </a>
                                        </p>
                                      </div>
                                    </div>
                                </form>
                          </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

accounts/templates/accounts/login_form.html
{% extends 'accounts/layout.html' %}
{% load bootstrap4 %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    <div id="signin" data-target-group="idForm">
      <!-- Title -->
          <header class="text-center mb-5">
            <h2 class="h4 mb-0">Please sign in</h2>
            <p>Signin to manage your account.</p>
          </header>
          <!-- End Title -->
        {% csrf_token %}
        {% bootstrap_form form%}
         <div class="mb-3">
            <button type="submit" class="btn btn-block btn-primary">로그인</button>
         </div>

      <div class="text-center mb-3">
        <p class="text-muted">
          계정이 없으신가요?
          <a class="js-animation-link" href="{% url 'accounts:signup' %}"
             data-link-group="idForm"
             data-animation-in="fadeIn">회원가입
          </a>
        </p>
      </div>
    </div>
</form>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends 'accounts/layout.html' %}
{% load bootstrap4 %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    <div id="signin" data-target-group="idForm">
      <!-- Title -->
          <header class="text-center mb-5">
            <h2 class="h4 mb-0">Please sign in</h2>
            <p>Signin to manage your account.</p>
          </header>
          <!-- End Title -->
        {% csrf_token %}
        {% bootstrap_form form%}
         <div class="mb-3">
            <button type="submit" class="btn btn-block btn-primary">암호변경</button>
         </div>
    </div>
</form>
{% endblock %}

accounts/templates/accounts/profile_edit_form.html
{% extends 'accounts/layout.html' %}
{% load bootstrap4 %}
{% block content %}
<div id="signup" data-target-group="idForm">
      <!-- Title -->
      <header class="text-center mb-5">
        <h2 class="h4 mb-0">Please sign up</h2>
        <p>Fill out the form to get started.</p>
      </header>
      <!-- End Title -->
    {% csrf_token %}
    {% bootstrap_form form%}
     <div class="mb-3">
        <button type="submit" class="btn btn-block btn-primary">프로필 수정</button>
      </div>
</div>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends 'accounts/layout.html' %}
{% load bootstrap4 %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    <div id="signup" data-target-group="idForm">
          <!-- Title -->
          <header class="text-center mb-5">
            <h2 class="h4 mb-0">Please sign up</h2>
            <p>Fill out the form to get started.</p>
          </header>
          <!-- End Title -->
        {% csrf_token %}
        {% bootstrap_form form%}
         <div class="mb-3">
            <button type="submit" class="btn btn-block btn-primary">회원가입</button>
          </div>

      <div class="text-center mb-3">
        <p class="text-muted">
          계정이 있으신가요?
          <a class="js-animation-link" href="{% url 'accounts:login' %}"
             data-link-group="idForm"
             data-animation-in="fadeIn">로그인
          </a>
        </p>
      </div>
    </div>
</form>
{% endblock %}