baseApp/urls.py
from django.urls import path
from baseApp import views

app_name = 'baseApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/',views.post_new,name='post_new'),
    path('post/prod/', views.post_list_prod, name='post_list_prod'),
    path('post/project/', views.post_list_project, name='post_list_project'),
    path('post/prod/<int:pk>/',views.post_detail_prod,name='post_detail_prod'),
    path('post/project/<int:pk>/',views.post_detail_project,name='post_detail_project'),
    # path('post/<int:pk>/like',views.post_like,name='post_like'),
    # path('post/<int:pk>/unlike',views.post_unlike,name='post_unlike'),
    # path('post/<int:post_pk>/comment/new',views.comment_new,name='comment_new'),
    # re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page,name='user_page'),
]

baseApp/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from ckeditor.fields import RichTextField
import re

from moonsoft.util import uuid_name_upload_to


class commonColModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract =True

class Post(commonColModel):
    #
    title = models.CharField(blank=True, max_length=200)
    class PostChoices(models.TextChoices):
        Product = "PD", "Product"
        Projects = "PJ", "Projects"
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='my_post_set', on_delete=models.CASCADE)
    tag = models.CharField(max_length=100, blank=True)
    postDivision = models.CharField(max_length=10,choices=PostChoices.choices)
    tag_set = models.ManyToManyField('Tag', blank=True)
    caption = models.CharField(max_length=500)
    thumnail = models.ImageField(upload_to=uuid_name_upload_to)
    body = RichTextUploadingField(blank=True, null=True)
    def __str__(self):
        return self.caption

    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.tag)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    def get_absolute_url(self):
        return reverse("baseApp:product_detail", args=[self.pk])

    # def save_model(self, request, obj, form, change):
    #     obj.user = request.user
    #     super().save_model(request, obj, form, change)

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Comment(commonColModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()
    class Meta:
        ordering = ['-id']

baseApp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import  HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages

# Create your views here.
# @login_required
from django.views.generic import ListView
from django.views.generic.edit import FormView, CreateView

from baseApp.form import PostForm, CommentForm
from baseApp.models import Post

paginate_by=12
class IndexListView(ListView):
    # timesince = timezone.now() - timedelta(days=3)
    model = Post
    template_name = "baseApp/index.html"
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page', '1')  # 페이지
        post_list = Post.objects.all().order_by('-created_at')
        paginator = Paginator(post_list, 6)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        context = {'post_list': page_obj}
        return context
index = IndexListView.as_view()

@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        formset = PostForm(request.POST, request.FILES)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_set.add(*post.extract_tag_list())
            messages.success(request, "포스팅을 저장했습니다.")
            return HttpResponseRedirect("/")  # To Do 상세화면으로 이동

    else:
        form = PostForm()
    return render(request, 'baseApp/post_form.html',
                  {'form': form,} )

# class PostListView(LoginRequiredMixin, ListView):
#     model=Post
#     paginate_by = 10
#     template_name = "baseApp/post_list_prod.html"
# post_list = PostListView.as_view()

class PostListViewProd(ListView):
    model = Post
    template_name = "baseApp/post_list_prod.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page', '1')  # 페이지
        post_list = Post.objects.all().filter(Q(postDivision="PD")).order_by('-created_at')
        paginator = Paginator(post_list, 6)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        context = {'post_list': page_obj, 'post_count': post_list.count(),}
        return context

post_list_prod = PostListViewProd.as_view()

class PostListViewProject(ListView):
    model=Post
    template_name = "baseApp/post_list_projects.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page', '1')  # 페이지
        post_list = Post.objects.all().filter(Q(postDivision="PJ")).order_by('-created_at')
        paginator = Paginator(post_list, 6)  # 페이지당 10개씩 보여주기
        page_obj = paginator.get_page(page)
        context = {'post_list': page_obj,'post_count':post_list.count(),}
        return context

post_list_project = PostListViewProject.as_view()

def post_detail_prod(request,pk):
    post = get_object_or_404(Post,  pk=pk) # 객체 즉 pk 가 존재 하지 않는 경우 404에러를 내기 위함
    comment_form = CommentForm()
    return render(request,"baseApp/post_detail.html",{
        'post':post,
        'comment_form' : comment_form,
    })

def post_detail_project(request,pk):
    post = get_object_or_404(Post,  pk=pk) # 객체 즉 pk 가 존재 하지 않는 경우 404에러를 내기 위함
    comment_form = CommentForm()
    return render(request,"baseApp/post_detail.html",{
        'post':post,
        'comment_form' : comment_form,
    })
# 함수 기반으로 코딩
#
# def post_list(request):
#     paginate_by = 10
#     fileSet_qs = FileSet.objects.filter(post=OuterRef("pk")).order_by("-id")
#     postDivision = request.GET['division']
#     qs = Post.objects.all().annotate(post_thumnail=Subquery(fileSet_qs.values("fileName")[:1])).filter(Q(postDivision=postDivision))
#     # 검색기능
#     q = request.GET.get('q', '')  # get 방식 없으면 '' 를 반환-''에 다른값을 넣을수 있음
#     if q:
#         qs = qs.filter(title__icontains=q)
#     # 검색기능
#     # photo = FileSet.objects.first().filter(Q(post=Post))
#     # instagram/templates/instagram/post_list_bak.html
#     return render(request, 'baseApp/post_list_bak.html', {
#         'post_list': qs,
#         'q': q,
#         'paginate_by': paginate_by,
#     })
# @login_required
# def post_new(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         formset = PostForm(request.POST, request.FILES)
#         if form.is_valid() and formset.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             post.tag_set.add(*post.extract_tag_list())
#             for file in request.FILES.getlist("file[]"):
#                 fileSet = FileSet.objects.create(post=post, fileName=file)
#                 fileSet.save()
#             messages.success(request, "포스팅을 저장했습니다.")
#             return HttpResponseRedirect("/")  # To Do 상세화면으로 이동
#
#     else:
#         form = PostForm()
#         formset = FileSetForm()
#     return render(request, 'baseApp/post_form.html',
#                   {'form': form, 'formset': formset}, )

baseApp/templates/baseApp/index.html
{% extends 'baseApp/layout.html' %}
{% load static %}
{% load bootstrap4 %}
{% load thumbnail%}
{% load humanize %}
{% block content %}
    <!-- ========== MAIN CONTENT ========== -->
    <main id="content">
        <!-- Hero Section -->
        <div class="gradient-overlay-half-dark-v3 bg-img-hero"
             style="background-image: url({% static 'mainImage/moonSoftMain/M-2_2_600.jpg' %}); width: 100%; height: 50%;object-fit: cover;">

            <!-- Main Content -->
            <div class="d-lg-flex align-items-lg-center height-85vh--lg">
                <div class="container ml-4 " style="margin-top: 100px ">
                    <div class="row justify-content-lg-between align-items-lg-center">
                        <div class="mb-7 mb-lg-0">
                            <!-- Title -->
                            <h1 class="font-size-35--md-down text-white mb-0">Welcome to MOONSOFT!</h1>
                            <h1 class="font-size-35--md-down text-white mb-0">Scientific and Technical Software Specialist</h1>
                            <!-- End Title -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Main Content -->
        </div>

    <div class="container space-2 space-1-top">
    </div>
        <div class="container space-1-bottom--lg">
          <div class="row">
            <div class="mb-9 mb-lg-0">
                {% for post in post_list %}
                        <div class="card-deck d-block d-lg-flex">
                            {% include "baseApp/post_latest.html" %}
                        </div>
                {% endfor %}
            <nav aria-label="Page navigation">
                    <ul class="pagination">
                    <!-- 이전페이지 -->
                    {% if post_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ post_list.previous_page_number }}" aria-label="이전">
                              <span aria-hidden="true">&laquo;</span>
                              <span class="sr-only">이전</span>
                            </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" >이전</a>
                    </li>
                    {% endif %}
                    <!-- 페이지리스트 -->
                    {% for page_number in post_list.paginator.page_range %}
                        {% if page_number == post_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                    <!-- 다음페이지 -->
                    {% if post_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ post_list.next_page_number }}" aria-label="다음">
                              <span aria-hidden="true">&raquo;</span>
                              <span class="sr-only">다음</span>
                            </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" >다음</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            </div>
          </div>
        </div>
    </main>
    <!-- ========== END MAIN CONTENT ========== -->
{% endblock %}

baseApp/templates/baseApp/layout.html
{% extends 'layout.html' %}

baseApp/templates/baseApp/layout_post.html
{% extends 'layout_post.html' %}

baseApp/templates/baseApp/post_album.html
{% load thumbnail%}
{% load humanize %}
{% load static %}

<article class="card border-0 mb-5">
  <div class="card-body row align-items-stretch no-gutters p-0">
    <!-- News Blog Card -->
    <div class="col-7 border border-right-0 rounded-left">
      <div class="p-5">
        <h2 class="h5 mb-3">
          <a href="{% url 'baseApp:post_detail_prod' post.pk %}">{{ post.title }}</a>
        </h2>
        <p class="mb-0">{{ post.caption }}</p>
      </div>
    </div>
    <img class="col-5 card-img-right border border-left-0 bg-img-hero" src="{{ post.thumnail.url }}"/>
{#                  <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{% thumbnail post.post_thumnail 512x512 crop %}"   alt="">#}
  </div>
  <!-- End News Blog Card -->
</article>

baseApp/templates/baseApp/post_detail.html
{% extends "baseApp/layout_post.html" %}
{% load bootstrap4 %}
{% block title %}
    Instagram / Post List
{% endblock title %}
{% block content %}

  <!-- ========== MAIN CONTENT ========== -->
  <main id="content">
  <div class="gradient-overlay-half-dark-v3 bg-img-hero"
             style="background-image: url({{post.thumnail.url}}); width: 100%; height: 400px;">
        <div class="d-lg-flex align-items-lg-center height-85vh--lg">
            <div class="container space-1-bottom--lg mb-lg-9">
                <div class="row justify-content-lg-between align-items-lg-center">
{#                        <div class="col-lg-5">#}
                        <!-- Title -->
{#                        <h4 class="d-block text-white mb-lg-9">{{ post.title}}</h4>#}
{#                            <h1 class="display-4 font-size-48--md- text-white mb-0">문소프트에 오신걸 환영합니다.</h1>#}
                        <!-- End Title -->
{#                        </div>#}
                </div>
            </div>
        </div>
            <!-- End Main Content -->
  </div>
    <div class="container space-3-top--lg">
      <h1>{{ post.title}} <small class="text-muted" style="font-size: 20px;">&nbsp;&nbsp;&nbsp;&nbsp;{{ post.created_at}}</small> </h1>
      <p class="lead">{{ post.caption}}</p>
    </div>
    <div class="container">
        <div id = "body"  style="overflow: auto">
                    {{ post.body|safe }}
        </div>
    </div>
  </main>
  <!-- ========== END MAIN CONTENT ========== -->
{% endblock %}

baseApp/templates/baseApp/post_latest.html
{% load thumbnail%}
{% load humanize %}

<article class="card border-0 mb-5">
  <div class="card-body row align-items-stretch no-gutters p-0">
    <!-- News Blog Card -->
    <div class="col-7 border border-right-0 rounded-left">
      <div class="p-5">
        <h1 class="h5 mb-3" style="font-weight:bold ">
          <a href="{% url 'baseApp:post_detail_prod' post.pk %}">{{ post.title }}</a>
        </h1>
          <h6 class="text-muted" style="">{{ post.caption }}</h6>
          <h6 class="text-muted" style="">{{ post.created_at|date:"Y.m.d" }}</h6>
      </div>
    </div>
      <img class="col-3 card-img-right border border-left-0 bg-img-hero" src="{{ post.thumnail.url }}"/>
  </div>
  <!-- End News Blog Card -->

</article>

baseApp/templates/baseApp/post_list_prod.html
{% extends "baseApp/layout_post.html" %}
{% load bootstrap4 %}
{% block title %}
    Products
{% endblock title %}
{% block content %}
 <main id="content">
    <!-- Hero Section -->
    <div class="container space-3-top--lg">
      <h2>Products : <span style="font-palette: light"> {{ post_count }} </span></h2>
    </div>
    <!-- End Hero Section -->
    <!-- News Blog Content -->
    <div class="container">
    <hr class="my-0 mb-9">
      <div class="row">
        <div class="mb-9 mb-lg-0">
            {% for post in post_list %}
                {% if forloop.counter|divisibleby:2 %}
                    {% include "baseApp/post_album.html" %}
                    </div>
                {% else %}
                    {% if forloop.last %}
                        <div class="card-deck d-block d-lg-flex">
                        {% include "baseApp/post_album.html" %}
                        </div>
                    {% else %}
                        <div class="card-deck d-block d-lg-flex">
                        {% include "baseApp/post_album.html" %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        <div class="mb-9"></div>

          <!-- Pagination -->
          <nav aria-label="Page navigation">
                <ul class="pagination">
                <!-- 이전페이지 -->
                {% if post_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ post_list.previous_page_number }}" aria-label="이전">
                          <span aria-hidden="true">&laquo;</span>
                          <span class="sr-only">이전</span>
                        </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" >이전</a>
                </li>
                {% endif %}
                <!-- 페이지리스트 -->
                {% for page_number in post_list.paginator.page_range %}
                    {% if page_number == post_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if post_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ post_list.next_page_number }}" aria-label="다음">
                          <span aria-hidden="true">&raquo;</span>
                          <span class="sr-only">다음</span>
                        </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" >다음</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        </div>
      </div>
    </div>
    <!-- End News Blog Content -->
  </main>
{% endblock content %}

baseApp/templates/baseApp/post_list_projects.html
{% extends "baseApp/layout_post.html" %}
{% load bootstrap4 %}
{% block title %}
    Projects
{% endblock title %}
{% block content %}
 <main id="content">
    <!-- Hero Section -->
    <div class="container space-2 space-3-top--lg">
      <h2>Projects : <span style="font-palette: light"> {{ post_count }} </span></h2>
    </div>
    <!-- End Hero Section -->

    <!-- News Blog Content -->
    <div class="container mt-4">
      <hr class="my-0 mb-4">
      <div class="row">
        <div class="mb-9 mb-lg-0">
            {% for post in post_list %}
                {% if forloop.counter|divisibleby:2 %}
                    {% include "baseApp/post_album.html" %}
                    </div>
                {% else %}
                    {% if forloop.last %}
                        <div class="card-deck d-block d-lg-flex">
                        {% include "baseApp/post_album.html" %}
                        </div>
                    {% else %}
                        <div class="card-deck d-block d-lg-flex">
                        {% include "baseApp/post_album.html" %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        <div class="mb-9"></div>

          <!-- Pagination -->
           <nav aria-label="Page navigation">
                <ul class="pagination">
                <!-- 이전페이지 -->
                {% if post_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ post_list.previous_page_number }}" aria-label="이전">
                          <span aria-hidden="true">&laquo;</span>
                          <span class="sr-only">이전</span>
                        </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" >이전</a>
                </li>
                {% endif %}
                <!-- 페이지리스트 -->
                {% for page_number in post_list.paginator.page_range %}
                    {% if page_number == post_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if post_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ post_list.next_page_number }}" aria-label="다음">
                          <span aria-hidden="true">&raquo;</span>
                          <span class="sr-only">다음</span>
                        </a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" >다음</a>
                </li>
                {% endif %}
            </ul>
        </nav>
          <!-- End Pagination -->
        </div>
      </div>
    </div>
    <!-- End News Blog Content -->
  </main>
{% endblock content %}